services:
  - type: web
    name: pocketbase-bookdirectstays
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8080 